export interface MetricInterpretation {
  metric: string;
  low_meaning: string;
  high_meaning: string;
  signal: string;
  desirable_when: string;
  risky_when: string;
}

export const METRIC_SIGNALS: Record<string, MetricInterpretation> = {
  avg_characters_per_word: {
    metric: "avg_characters_per_word",
    low_meaning: "Uses simple, short words.",
    high_meaning: "Uses complex, multisyllabic, or academic vocabulary.",
    signal: "Vocabulary sophistication and technical density.",
    desirable_when: "Technical precision is required for expert audiences.",
    risky_when: "Writing for the general public or when high accessibility is needed.",
  },
  avg_words_per_sentence: {
    metric: "avg_words_per_sentence",
    low_meaning: "Punchy, direct, and fast-paced.",
    high_meaning: "Elaborate, complex, or potentially rambling.",
    signal: "Cognitive load and rhythmic pace.",
    desirable_when: "Explaining complex concepts that require nuance.",
    risky_when: "Mobile reading or low-literacy audiences.",
  },
  sentence_length_p90: {
    metric: "sentence_length_p90",
    low_meaning: "Consistent, controlled sentence lengths.",
    high_meaning: "Presence of very long 'outlier' sentences.",
    signal: "Structural 'tails' that can break reader flow.",
    desirable_when: "Literary variety is intended.",
    risky_when: "The long sentences become hard to parse (sentence-tail risk).",
  },
  difficult_word_ratio: {
    metric: "difficult_word_ratio",
    low_meaning: "Uses common, familiar vocabulary.",
    high_meaning: "Uses specialized, rare, or jargon-heavy terms.",
    signal: "Accessibility and educational requirement.",
    desirable_when: "Writing for specialists (medical, legal, technical).",
    risky_when: "Communication should be inclusive or global.",
  },
  lexical_diversity_ttr: {
    metric: "lexical_diversity_ttr",
    low_meaning: "Repetitive or limited vocabulary.",
    high_meaning: "Rich, varied vocabulary.",
    signal: "Vocabulary breadth and repetition control.",
    desirable_when: "Creative writing or descriptive prose.",
    risky_when: "Clarity depends on consistent terminology (e.g., UI labels).",
  },
  avg_words_per_paragraph: {
    metric: "avg_words_per_paragraph",
    low_meaning: "Highly scannable, mobile-friendly blocks.",
    high_meaning: "Denser 'walls of text'.",
    signal: "Visual scannability and information grouping.",
    desirable_when: "Deep academic or narrative immersion.",
    risky_when: "Web content, newsletters, or quick-reference docs.",
  },
  heading_density: {
    metric: "heading_density",
    low_meaning: "Continuous prose with few breaks.",
    high_meaning: "Highly structured with frequent signposts.",
    signal: "Navigational ease and structural signaling.",
    desirable_when: "Long-form guides or technical references.",
    risky_when: "Narrative fiction or personal essays (can feel disjointed).",
  },
  dialogue_ratio: {
    metric: "dialogue_ratio",
    low_meaning: "Narration or exposition heavy.",
    high_meaning: "Character-driven and conversational.",
    signal: "Scene immediacy and character interaction.",
    desirable_when: "Character-driven scenes and fast pacing.",
    risky_when: "Internal monologue or world-building is the goal.",
  },
  wall_of_text_risk: {
    metric: "wall_of_text_risk",
    low_meaning: "Well-broken text with frequent breaks.",
    high_meaning: "Long stretches of text without headings or paragraph breaks.",
    signal: "Reader fatigue and bounce risk.",
    desirable_when: "Never really desirable for digital reading.",
    risky_when: "The reader needs to find information quickly.",
  },
  repetition_ratio: {
    metric: "repetition_ratio",
    low_meaning: "Varied word choice.",
    high_meaning: "Frequent use of the same words.",
    signal: "Prose 'echoes' and vocabulary variety.",
    desirable_when: "Reinforcing a specific keyword or brand name.",
    risky_when: "It feels unintentional or shows lack of vocabulary.",
  },
  lexical_diversity_mattr: {
    metric: "lexical_diversity_mattr",
    low_meaning: "Limited vocabulary within local windows.",
    high_meaning: "Consistently rich vocabulary throughout.",
    signal: "Vocabulary variety independent of text length.",
    desirable_when: "High-quality professional writing.",
    risky_when: "Technical docs requiring extreme consistency.",
  },
  sentence_length_stddev: {
    metric: "sentence_length_stddev",
    low_meaning: "Monotonous or rhythmic sentence pacing.",
    high_meaning: "High variety in sentence rhythm.",
    signal: "Prose cadence and reader engagement.",
    desirable_when: "Narrative fiction or engaging essays.",
    risky_when: "Technical instructions where consistency aids parsing.",
  },
  paragraph_cadence_variation: {
    metric: "paragraph_cadence_variation",
    low_meaning: "Uniform paragraph sizing.",
    high_meaning: "Dynamic, varied paragraph lengths.",
    signal: "Visual rhythm and structural variety.",
    desirable_when: "Engaging blog posts or fiction.",
    risky_when: "Formal reports or structured manuals.",
  },
  paragraph_scannability_score: {
    metric: "paragraph_scannability_score",
    low_meaning: "Hard to scan; dense blocks.",
    high_meaning: "Easy to skim; well-distributed information.",
    signal: "Skimmability and information accessibility.",
    desirable_when: "Landing pages and web content.",
    risky_when: "Immersion is more important than speed.",
  },
  scene_density_proxy: {
    metric: "scene_density_proxy",
    low_meaning: "Static or abstract content.",
    high_meaning: "Active, immediate narrative movement.",
    signal: "Narrative momentum and scene presence.",
    desirable_when: "Thriller or action-oriented fiction.",
    risky_when: "Philosophical or world-building sections.",
  },
  exposition_density_proxy: {
    metric: "exposition_density_proxy",
    low_meaning: "Action or dialogue heavy.",
    high_meaning: "Information or background heavy.",
    signal: "Background density and world-building.",
    desirable_when: "Introductory chapters or complex world-building.",
    risky_when: "Mid-scene where pace should be high.",
  },
  sensory_term_density: {
    metric: "sensory_term_density",
    low_meaning: "Grounded in few physical details.",
    high_meaning: "Richly detailed with sensory imagery (visual, auditory, tactile).",
    signal: "Narrative immersion and 'showing' vs 'telling'.",
    desirable_when: "Atmospheric scenes or character introductions.",
    risky_when: "Instructional writing or fast-paced action.",
  },
  abstract_word_ratio: {
    metric: "abstract_word_ratio",
    low_meaning: "Grounded and concrete language.",
    high_meaning: "Vague, conceptual, or philosophical language.",
    signal: "Conceptual density vs concrete grounding.",
    desirable_when: "Philosophical essays or high-level strategic summaries.",
    risky_when: "Action scenes or instructional guides where clarity is paramount.",
  },
  sentence_tail_risk_score: {
    metric: "sentence_tail_risk_score",
    low_meaning: "Sentences are easy to hold in working memory.",
    high_meaning: "Sentences are 'back-heavy' with complex clauses at the end.",
    signal: "Cognitive load and parsing difficulty.",
    desirable_when: "Rarely desirable; can be used for 'academic' flavor.",
    risky_when: "Communication must be clear and rapidly understood.",
  },
};
